name: 'GitHub Pages Build'
description: 'Rebuilds GitHub Pages using Pages API'
inputs:
  username:
    description: 'GitHub username'
    required: true
  api_token:
    description: 'GitHub API token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.api_token }}