name: Build
on: [push, pull_request]

jobs:
  filediff:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    #     outputs:
    #       all: ${{ steps.changes.outputs.all}}
    #       ts: ${{ steps.changes.outputs.ts }}
    steps:
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.sha }} | xargs)"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
