name: Rebuild site

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 * * *'

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    # Standard usage
    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.API_TOKEN }}